apiVersion: batch/v1
kind: Job
metadata:
  name: lh-2
spec:
  completions: 70
  parallelism: 70
  template:
    spec:
      # our pod both tolerates and REQUIRES the special LH nodes
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "lighthouse"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - lighthouse
      containers:
        - name: lh
          image: kporras07/lighthouse-ci
          resources:
            requests:
              memory: "1Gi"
          args:
          - https://kubernetesfordogs.com

      restartPolicy: Never
  backoffLimit: 4
